input:
  - type: rabbitmq
    host: localhost
    port: 5672
    queue: logging_update
    username: test
    password: test
output:
  - type: elastic
    url: ["http://localhost:9200"]
    index: "logging%{+200601}"
    document_type: "logs"
    document_id: "%{message_id}"
    action: update
    retriable_code: [404]
    retry_initial_interval: 3
    retry_max_interval: 10
    bulk_flush_interval: 10

