input:
  - type: redis
    host: localhost:6379
    key:  hello
    connections: 1

output:
  - type: amqp
    urls: ["amqp://test:test@localhost:5672/"]
    exchange: logs_direct
    exchange_type: "fanout"
    exchange_durable: true
    exchange_auto_delete: false
    bind_queues: ["hh", "kk"]
    queue_durable: true

